{
 "title": "Kubeclarity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Applications",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kc_counter_applications", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Vulnerabilitiy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kc_counter_vuln)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Fix Vulnerabilitiy ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kc_counter_vuln_fix)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Packages",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kc_counter_packages", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Resources",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kc_counter_resources", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total License",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kc_counter_license)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Vulnerability with Severity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kc_counter_vuln - 0 ", "legendFormat": "{{ severity }}" }
   ]
  },
  {
   "title": "Total Fix Vulnerability with Severity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kc_counter_vuln_fix - 0 ", "legendFormat": "{{ severity }}" }
   ]
  },
  {
   "title": "Top 10 License",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10, kc_counter_license)", "legendFormat": "{{ license }}" }
   ]
  },
  {
   "title": "Language Stats",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kc_counter_language", "legendFormat": "{{ language }}" }
   ]
  }
 ]
}